- name: Install the flatpak io.dbeaver.DBeaverCommunity
  community.general.flatpak:
    name: io.dbeaver.DBeaverCommunity
    state: present

- name: Install the flatpak org.jdownloader.JDownloader
  community.general.flatpak:
    name: org.jdownloader.JDownloader
    state: present

