- name: Install Flatpak applications
  community.general.flatpak:
    name: "{{ item.package }}"
    state: present
  loop:
    - { package: "io.dbeaver.DBeaverCommunity" }
    - { package: "org.jdownloader.JDownloader" }
    - { package: "com.slack.Slack" }

