- stat:
    path: /etc/zypp/repos.d/home_Dead_Mozay.repo
  register: repo_home_Dead_Mozay

- name: Add repository "home:Dead_Mozay"
  when: >
    not repo_home_Dead_Mozay.stat.exists
    and ansible_facts['distribution_version'] in ['15.5', '15.6']
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/home:Dead_Mozay/{{ ansible_facts['distribution_version'] }}/home:Dead_Mozay.repo"

- stat:
    path: /etc/zypp/repos.d/home_ecsos.repo
  register: repo_home_ecsos

- name: Add repository "home:ecsos"
  when: >
    not repo_home_ecsos.stat.exists
    and ansible_facts['distribution_version'] in ['15.5', '15.6']
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/home:ecsos/{{ ansible_facts['distribution_version'] }}/home:ecsos.repo"

- stat:
    path: /etc/zypp/repos.d/home_jirislaby_kotatko.repo
  register: repo_home_jirislaby_kotatko

- name: Add repository "home:jirislaby:kotatko"
  when: >
    not repo_home_jirislaby_kotatko.stat.exists
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/home:jirislaby:kotatko/{{ ansible_facts['distribution_version'] }}/home:jirislaby:kotatko.repo"

- name: Import repo keys and refresh
  command: zypper --gpg-auto-import-keys refresh

- name: "Install required packages"
  zypper:
    state: present
    name: ['krusader', 'hugin', 'datovka']

