- name: Remove repository "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/pool/"
  when: ansible_facts['os_family']|lower == 'suse'
  zypper_repository:
    state: absent
    repo: "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/pool/"
  loop:
    - SLE-15-SP1
    - SLE-15-SP2
    - SLE-15-SP3
    - SLE-15-SP4
    - SLE-15-SP5
- name: Remove repository "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/toberemoved/"
  when: ansible_facts['os_family']|lower == 'suse'
  zypper_repository:
    state: absent
    repo: "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/toberemoved/"
  loop:
    - SLE-15-SP1
    - SLE-15-SP2
    - SLE-15-SP3
    - SLE-15-SP4
    - SLE-15-SP5

- stat:
    path: /etc/zypp/repos.d/filesystems.repo
  register: repo_file

- name: Add repository "filesystems"
  when: not repo_file.stat.exists
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/filesystems/${releasever}/filesystems.repo"

- stat:
    path: /etc/zypp/repos.d/home_inescid_grid.repo
  register: repo_home_inescid_grid

- name: Add repository "home:inescid:grid (new version of ansible)"
  when: >
    not repo_home_inescid_grid.stat.exists
    and ansible_facts['distribution_version'] in ['15.5', '15.6']
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/home:inescid:grid/${releasever}/home:inescid:grid.repo"

- stat:
    path: /etc/zypp/repos.d/home_regataos.repo
  register: repo_home_regataos

- name: Add repository "home:regataos (MANY OS packages)"
  when: >
    not repo_home_regataos.stat.exists
    and ansible_facts['distribution_version'] in ['15.4', '15.5']
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/home:regataos/${releasever}/home:regataos.repo"

- name: Import repo keys and refresh
  command: zypper --gpg-auto-import-keys refresh

- name: "Install required packages"
  zypper:
    state: present
    name: ['ansible', 'mc', 'vim', 'tmux', 'docker', 'docker-compose', 'ncdu', 'compsize', 'git', 'wireguard-tools', 'mosh', 'links', 'iotop', 'sysstat', 'openfortivpn', 'sshfs', 'ffmpeg']

