- name: "Update apt package cache"
  apt:
    update_cache: yes

- name: "Install required packages"
  apt:
    state: present
    name: ['ansible', 'mc', 'vim', 'tmux', 'docker.io', 'ncdu', 'btrfs-compsize', 'git', 'wireguard', 'flatpak', 'iotop', 'rclone']

- name: "Add flathub repo in flatpak"
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
