- name: "Update apt package cache"
  apt:
    update_cache: yes

- name: "Install required packages"
  apt:
    state: present
    name: ['ansible', 'mc', 'vim', 'tmux', 'docker.io', 'docker-compose', 'ncdu', 'btrfs-compsize', 'git', 'wireguard', 'flatpak']
