- name: Remove repository "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/pool/"
  when: ansible_facts['os_family']|lower == 'suse'
  zypper_repository:
    state: absent
    repo: "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/pool/"
  loop:
    - SLE-15-SP1
    - SLE-15-SP2
    - SLE-15-SP3
    - SLE-15-SP4
    - SLE-15-SP5
- name: Remove repository "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/toberemoved/"
  when: ansible_facts['os_family']|lower == 'suse'
  zypper_repository:
    state: absent
    repo: "https://download.opensuse.org/repositories/SUSE:/{{ item }}:/GA/toberemoved/"
  loop:
    - SLE-15-SP1
    - SLE-15-SP2
    - SLE-15-SP3
    - SLE-15-SP4
    - SLE-15-SP5

- stat:
    path: /etc/zypp/repos.d/filesystems.repo
  register: repo_file

- name: Add repository "filesystems"
  when: not repo_file.stat.exists
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/filesystems/{{ ansible_facts['distribution_version'] }}/filesystems.repo"

- stat:
    path: /etc/zypp/repos.d/home_txutxifel.repo
  register: repo_home_txutxifel

- name: Add repository "home:txutxifel (snapd, ...)"
  when: >
    not repo_home_txutxifel.stat.exists
    and ansible_facts['distribution_version'] in ['15.5', '15.6']
  zypper_repository:
    state: present
    repo: "https://download.opensuse.org/repositories/home:txutxifel/{{ ansible_facts['distribution_version'] }}/home:txutxifel.repo"

- name: Import repo keys and refresh
  command: zypper --gpg-auto-import-keys refresh

- name: "Install required packages"
  zypper:
    state: present
    name: ['ansible', 'mc', 'vim', 'tmux', 'docker', 'docker-compose', 'ncdu', 'compsize', 'git', 'wireguard-tools', 'mosh', 'links']

- name: "Install required packages on openSUSE 15.5 and 15.6"
  when: >
    ansible_facts['distribution_version'] in ['15.5', '15.6']
  zypper:
    state: present
    name: ['snapd']

